# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x07IdAudio\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x36\n\x0c\x41udioService\x12&\n\x0bStreamAudio\x12\x08.IdAudio\x1a\x0b.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=15
  _globals['_AUDIOCHUNK']._serialized_end=41
  _globals['_IDAUDIO']._serialized_start=43
  _globals['_IDAUDIO']._serialized_end=64
  _globals['_AUDIOSERVICE']._serialized_start=66
  _globals['_AUDIOSERVICE']._serialized_end=120
# @@protoc_insertion_point(module_scope)
